Repository etiquettestartshere/effectivetray, pull requests merged in 2024-07, with the labels that each got.

#89 icon to img
  README.md
  img/application.webp
  img/settings.webp
  module.json
  scripts/api.mjs
  scripts/effective-tray.mjs
Labels: documentation, foundryvtt

#92 [#91] Add socket event for `ActiveEffect5e#addDependent`.
  scripts/effective-tray.mjs
Labels: bug, effects

#93 3.3
  module.json
Labels: dnd5e system
